# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotofile.proto\x12\x08messages\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x0eMessageRequest\x12\x12\n\nany_string\x18\x01 \x01(\t\x12,\n\x08\x64\x61tetime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bgrpc_string\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"9\n\x0bMessageList\x12*\n\x08messages\x18\x01 \x03(\x0b\x32\x18.messages.MessageRequest2\x8c\x01\n\x0eMessageService\x12\x43\n\x0cStoreMessage\x12\x18.messages.MessageRequest\x1a\x19.messages.MessageResponse\x12\x35\n\x0bGetMessages\x12\x0f.messages.Empty\x1a\x15.messages.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=62
  _globals['_MESSAGEREQUEST']._serialized_end=181
  _globals['_MESSAGERESPONSE']._serialized_start=183
  _globals['_MESSAGERESPONSE']._serialized_end=216
  _globals['_EMPTY']._serialized_start=218
  _globals['_EMPTY']._serialized_end=225
  _globals['_MESSAGELIST']._serialized_start=227
  _globals['_MESSAGELIST']._serialized_end=284
  _globals['_MESSAGESERVICE']._serialized_start=287
  _globals['_MESSAGESERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
