version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo-gRPC
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - net1

  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: grpc_server
    ports:
      - "50051:50051"
    environment:
      MONGODB_HOSTNAME: mongodb  # Nombre del contenedor de MongoDB en la red interna
    depends_on:
      - mongodb
    networks:
      - net1

  grpc_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: grpc_client
    depends_on:
      - grpc_server
    networks:
      - net1

volumes:
  mongo-data:
    driver: local

networks:
  net1:
    driver: bridge
